# handlers/form_states.py
from aiogram.fsm.state import StatesGroup, State

class Form(StatesGroup):
    start = State()
    telegram_id = State()
    new_address = State()
    city = State()
    street = State()
    house = State()
    entrance = State()
    floor = State()
    apartment = State()
    address_confirm = State()
    service = State()
    electricity_type = State()
    elec_one_current = State()
    elec_one_previous = State()
    elec_two_current_day = State()
    elec_two_current_night = State()
    elec_two_previous_day = State()
    elec_two_previous_night = State()
    elec_three_current_peak = State()
    elec_three_current_day = State()
    elec_three_current_night = State()
    elec_three_previous_peak = State()
    elec_three_previous_day = State()
    elec_three_previous_night = State()
    gas_current = State()
    gas_previous = State()
    trash_unloads = State()
    trash_bins = State()
    bill_address = State()
    bill_detail = State()
    select_address = State()
